include:
  - stacks/postgres/docker-compose.yml
  - stacks/redis/docker-compose.yml
  - stacks/yamtrack/docker-compose.yml
  - stacks/jellystat/docker-compose.yml
  - stacks/navidrome/docker-compose.yml
  - stacks/paperless-ngx/docker-compose.yml
  - stacks/mealie/docker-compose.yml
