networks:
  internal:
    name: internal
    external: false
  dokploy-network:
    name: dokploy-network
    external: true

services:
  scrob:
    image: bellamy/scrob:${SCROB_TAG:-latest}
    container_name: scrob
    hostname: scrob
    restart: unless-stopped
    # pull_policy: always
    environment:
        TZ: ${TZ:-Africa/Nairobi}
        DATABASE_URL: ${DATABASE_URL:?DATABASE_URL IS required}
        SECRET_KEY: ${SECRET:?SECRET IS required}
        ENABLE_REGISTRATIONS: ${REGISTRATION:-false}
        REQUIRE_EMAIL_VALIDATION: ${REQUIRE_EMAIL_VALIDATION:-false}
        REGISTRATION_MAX_ALLOWED_USERS: ${REGISTRATION_MAX_ALLOWED_USERS:-0}
    ports:
      - "127.0.0.1:8900:7330"
    networks:
      - dokploy-network
      - internal
    volumes:
      - scrob-data:/app/backend/data
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  scrob-data:
    name: scrob-data
    driver: local