services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    restart: unless-stopped
    init: true
    container_name: seerr
    hostname: seerr
    network_mode: host
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      TZ: ${TZ:-Africa/Nairobi}
      PORT: 5055
    volumes:
      - seer-data:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

volumes:
  seer-data:
    name: seer-data