services:
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    hostname: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_IP: ${DB_HOST:-postgres}
      POSTGRES_PORT: ${DB_PORT:-5432}
      POSTGRES_USER: ${DB_USERNAME:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      POSTGRES_DB: ${DB_DATABASE:-jellystat}
    ports:
      - 3000
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dokploy-network:
    external: true
